### ISSUE TITLE
Share ACID / CAP of vector DB

### ISSUE THREAD

**Issue by TheWeaVer** [TheWeaVer/lia#12]
**Motivation**
#11 introduces notion of vector db. If there is a page that can understand the characteristics of vector db, it would be useful one to us.

**Comment by zozond** [comment]
Did you mean `CAP` ? Not `CAS`?

**Comment by TheWeaVer** [comment]
Oh, yes. CAP 😅 Let me revise title.

**Comment by TheWeaVer** [comment]
@zozond , When you write `Closes #issue-number` on PR description, then, related issues are closed when the PR is merged. Then, you don't need to close issue by yourself. This is what I ask for 🙂
